# House Price Prediction

## About the dataset (House Pricing prediction data) 

**price:** Value of the house 

**resid_area:** Preporsion of residential area in the town

**air_qual:** Quality of Air in that neighborhood

**room_num:** Avearge number of rooms in houses of that locality

**age:** How old is the house counstuction  in years

**dist1:** Distance from employment hub 1

**dist2:** Distance from employment hub 2

**dist3:** Distance from employment hub 3

**dist4:** Distance from employment hub 4

**teachers:** Number of Teachers per 1000 population in the town

**poor_prop:** Preportion of poor population in the town

**airport:** Is there an airport in city? (Yes/No)

**n_hos_beds:** Number of Hospital Beds per 1000 population in the town

**n_hot_rooms:** Number of Hotel rooms per 1000 population in town

**waterbody:** What type of natural fresh water sourcs is there in the city (Lake/River/Both/None)

**rainfall:** The yearly average rainfall in centimeters

**bus_ter:** Is there a bus terminal in city? (Yes/No)

**parks:** Proportion of land assigned as park and green areas in town

**Sold:** Is house sold or not (0-No/1-Yes)

# Import Libraries

**Let us import the required libraries.**

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from warnings import filterwarnings
filterwarnings('ignore')

pd.options.display.max_columns = None
pd.options.display.max_rows = None
 
# to display the float values upto 6 decimal places     
pd.options.display.float_format = '{:.6f}'.format

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler 

# import various functions from sklearn
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.model_selection import GridSearchCV

# import the functions for visualizing the decision tree
#import pydotplus
#from IPython.display import Image  

# import various functions from statsmodels
import statsmodels
import statsmodels.api as sm

In [2]:
plt.rcParams['figure.figsize'] = [15,8]

# Data Preparation

In [21]:

df_houseprice = pd.read_csv("House-Price.csv")
df_houseprice

,price,resid_area,air_qual,room_num,age,dist1,dist2,dist3,dist4,teachers,poor_prop,airport,n_hos_beds,n_hot_rooms,waterbody,rainfall,bus_ter,parks,Sold
0,24.000000,32.310000,0.538000,6.575000,65.200000,4.350000,3.810000,4.180000,4.010000,24.700000,4.980000,YES,5.480000,11.192000,River,23,YES,0.049347,0
1,21.600000,37.070000,0.469000,6.421000,78.900000,4.990000,4.700000,5.120000,5.060000,22.200000,9.140000,NO,7.332000,12.172800,Lake,42,YES,0.046146,1
2,34.700000,37.070000,0.469000,7.185000,61.100000,5.030000,4.860000,5.010000,4.970000,22.200000,4.030000,NO,7.394000,101.120000,None,38,YES,0.045764,0
3,33.400000,32.180000,0.458000,6.998000,45.800000,6.210000,5.930000,6.160000,5.960000,21.300000,2.940000,YES,9.268000,11.267200,Lake,45,YES,0.047151,0
4,36.200000,32.180000,0.458000,7.147000,54.200000,6.160000,5.860000,6.370000,5.860000,21.300000,5.330000,NO,8.824000,11.289600,Lake,55,YES,0.039474,0
5,28.700000,32.180000,0.458000,6.430000,58.700000,6.220000,5.800000,6.230000,5.990000,21.300000,5.210000,YES,7.174000,14.229600,None,53,YES,0.045910,1
6,22.900000,37.870000,0.524000,6.012000,66.600000,5.870000,5.470000,5.700000,5.200000,24.800000,12.430000,YES,6.958000,12.183200,River,41,YES,0.052170,1
7,22.100000,37.870000,0.524000,6.172000,96.100000,6.040000,5.850000,6.250000,5.660000,24.800000,19.150000,NO,5.842000,12.176800,Lake,56,YES,0.057075,1
8,16.500000,37.870000,0.524000,5.631000,100.000000,6.180000,5.850000,6.300000,6.000000,24.800000,29.930000,YES,5.930000,12.132000,None,55,YES,0.056302,0
9,18.900000,37.870000,0.524000,6.004000,85.900000,6.670000,6.550000,6.850000,6.290000,24.800000,17.100000,YES,9.478000,14.151200,River,45,YES,0.050727,0
10,15.000000,37.870000,0.524000,6.377000,94.300000,6.650000,6.310000,6.550000,5.880000,24.800000,20.450000,NO,6.000000,11.120000,Lake,29,YES,0.057775,1
11,18.900000,37.870000,0.524000,6.009000,82.900000,6.270000,5.930000,6.510000,6.190000,24.800000,13.270000,NO,9.278000,13.151200,Lake and River,23,YES,0.055237,1
12,21.700000,37.870000,0.524000,5.889000,39.000000,5.760000,5.140000,5.580000,5.330000,24.800000,15.710000,YES,5.534000,10.173600,Lake and River,57,YES,0.057423,1
13,20.400000,38.140000,0.538000,5.949000,61.800000,4.720000,4.590000,4.930000,4.590000,19.000000,8.260000,YES,5.908000,14.163200,None,39,YES,0.053464,0
14,18.200000,38.140000,0.538000,6.096000,84.500000,4.600000,4.200000,4.480000,4.580000,19.000000,10.260000,NO,6.964000,13.145600,None,49,YES,0.059882,0
15,19.900000,38.140000,0.538000,5.834000,56.500000,4.600000,4.350000,4.720000,4.320000,19.000000,8.470000,YES,8.498000,14.159200,River,28,YES,0.059751,0
16,23.100000,38.140000,0.538000,5.935000,29.300000,4.660000,4.390000,4.520000,4.430000,19.000000,6.580000,NO,5.462000,10.184800,None,46,YES,0.054699,0
17,17.500000,38.140000,0.538000,5.990000,81.700000,4.560000,4.150000,4.360000,3.970000,19.000000,14.670000,NO,5.450000,11.140000,Lake,56,YES,0.054785,1
18,20.200000,38.140000,0.538000,5.456000,36.600000,3.800000,3.520000,3.860000,4.000000,19.000000,11.690000,YES,8.504000,12.161600,Lake and River,41,YES,0.054251,0
19,18.200000,38.140000,0.538000,5.727000,69.500000,3.980000,3.650000,4.000000,3.570000,19.000000,11.280000,NO,8.564000,12.145600,Lake and River,27,YES,0.057770,1
20,13.600000,38.140000,0.538000,5.570000,98.100000,3.930000,3.590000,4.090000,3.580000,19.000000,21.020000,YES,8.272000,15.108800,Lake and River,44,YES,0.048318,0
21,19.600000,38.140000,0.538000,5.965000,89.200000,4.110000,3.720000,4.340000,3.880000,19.000000,13.830000,YES,9.192000,14.156800,None,23,YES,0.054041,0
22,15.200000,38.140000,0.538000,6.142000,91.700000,4.180000,3.980000,4.310000,3.450000,19.000000,18.720000,YES,5.804000,14.121600,River,48,YES,0.057414,1
23,14.500000,38.140000,0.538000,5.813000,100.000000,4.350000,3.980000,4.130000,3.920000,19.000000,19.880000,YES,7.490000,13.116000,Lake,29,YES,0.052609,0
24,15.600000,38.140000,0.538000,5.924000,94.100000,4.690000,4.070000,4.720000,4.120000,19.000000,16.300000,YES,8.212000,13.124800,Lake,27,YES,0.050109,1
25,13.900000,38.140000,0.538000,5.599000,85.700000,4.690000,4.330000,4.720000,4.080000,19.000000,16.510000,YES,9.378000,13.111200,River,35,YES,0.051585,0
26,16.600000,38.140000,0.538000,5.813000,90.300000,4.940000,4.590000,4.710000,4.490000,19.000000,14.810000,NO,9.732000,12.132800,Lake,59,YES,0.047533,1
27,14.800000,38.140000,0.538000,6.047000,88.800000,4.500000,4.400000,4.600000,4.310000,19.000000,17.280000,YES,8.696000,13.118400,Lake,20,YES,0.048746,1
28,18.400000,38.140000,0.538000,6.495000,94.400000,4.570000,4.350000,4.690000,4.210000,19.000000,12.800000,YES,5.968000,15.147200,River,35,YES,0.054327,1
29,21.000000,38.140000,0.538000,6.674000,87.300000,4.530000,3.940000,4.360000,4.130000,19.000000,11.980000,NO,9.020000,12.168000,River,50,YES,0.048770,0
30,12.700000,38.140000,0.538000,5.713000,94.100000,4.520000,4.180000,4.370000,3.860000,19.000000,22.600000,NO,9.854000,12.101600,Lake,34,YES,0.058542,0
31,14.500000,38.140000,0.538000,6.072000,100.000000,4.390000,4.060000,4.480000,3.770000,19.000000,13.040000,YES,9.290000,12.116000,None,23,YES,0.052254,1
32,13.200000,38.140000,0.538000,5.950000,82.000000,4.010000,3.860000,4.310000,3.790000,19.000000,27.710000,NO,8.764000,14.105600,River,25,YES,0.053285,0
33,13.100000,38.140000,0.538000,5.701000,95.000000,3.800000,3.670000,3.960000,3.720000,19.000000,18.350000,YES,8.362000,15.104800,None,25,YES,0.057017,1
34,13.500000,38.140000,0.538000,6.096000,96.900000,4.070000,3.660000,3.870000,3.440000,19.000000,20.340000,YES,9.670000,11.108000,None,40,YES,0.049603,0
35,18.900000,35.960000,0.499000,5.933000,68.200000,3.690000,3.270000,3.540000,2.940000,20.800000,9.680000,YES,9.478000,11.151200,River,43,YES,0.052912,1
36,20.000000,35.960000,0.499000,5.841000,61.400000,3.390000,3.280000,3.620000,3.220000,20.800000,11.410000,NO,7.500000,15.160000,None,39,YES,0.045357,0
37,21.000000,35.960000,0.499000,5.850000,41.500000,3.980000,3.750000,4.120000,3.890000,20.800000,8.770000,YES,8.120000,10.168000,River,21,YES,0.050975,0
38,24.200000,35.960000,0.499000,5.966000,30.200000,4.150000,3.660000,4.040000,3.540000,20.800000,10.130000,YES,8.184000,10.193600,River,21,YES,0.048389,1
39,30.800000,32.950000,0.428000,6.595000,21.800000,5.650000,5.350000,5.550000,5.050000,21.700000,4.320000,YES,6.916000,12.246400,River,49,YES,0.045051,1
40,34.900000,32.950000,0.428000,7.024000,15.800000,5.630000,5.310000,5.530000,5.140000,21.700000,1.980000,YES,6.198000,15.279200,River,20,YES,0.042762,1
41,26.600000,36.910000,0.448000,6.770000,2.900000,5.770000,5.720000,6.000000,5.400000,22.100000,4.840000,NO,7.732000,13.212800,Lake and River,30,YES,0.049439,1
42,25.300000,36.910000,0.448000,6.169000,6.600000,5.930000,5.460000,5.880000,5.620000,22.100000,5.810000,NO,8.106000,15.202400,River,52,YES,0.041830,1
43,24.700000,36.910000,0.448000,6.211000,6.500000,6.040000,5.660000,5.840000,5.340000,22.100000,7.440000,YES,6.094000,15.197600,River,56,YES,0.044819,1
44,21.200000,36.910000,0.448000,6.069000,40.000000,5.810000,5.510000,5.900000,5.670000,22.100000,9.550000,NO,9.024000,12.169600,River,53,YES,0.039937,0
45,19.300000,36.910000,0.448000,5.682000,33.800000,5.230000,4.950000,5.210000,5.020000,22.100000,10.210000,NO,8.086000,11.154400,River,21,YES,0.044496,0
46,20.000000,36.910000,0.448000,5.786000,33.300000,5.250000,5.000000,5.400000,4.750000,22.100000,14.150000,YES,9.300000,12.160000,Lake,39,YES,0.045462,0
47,16.600000,36.910000,0.448000,6.030000,85.500000,5.830000,5.640000,5.750000,5.540000,22.100000,18.800000,YES,5.332000,12.132800,River,44,YES,0.052566,0
48,14.400000,36.910000,0.448000,5.399000,95.300000,5.980000,5.680000,5.960000,5.860000,22.100000,30.810000,NO,7.088000,14.115200,None,34,YES,0.042666,0
49,19.400000,36.910000,0.448000,5.602000,62.000000,6.110000,5.900000,6.300000,6.040000,22.100000,16.200000,NO,5.988000,13.155200,Lake and River,45,YES,0.050610,0
50,19.700000,35.640000,0.439000,5.963000,45.700000,7.080000,6.550000,7.000000,6.630000,23.200000,13.450000,YES,NaN,11.157600,River,21,YES,0.040389,1
51,20.500000,35.640000,0.439000,6.115000,63.000000,7.040000,6.740000,7.080000,6.410000,23.200000,9.430000,YES,7.010000,11.164000,Lake,30,YES,0.047270,1
52,25.000000,35.640000,0.439000,6.511000,21.100000,7.020000,6.760000,7.120000,6.370000,23.200000,5.280000,NO,9.900000,14.200000,River,56,YES,0.046152,1
53,23.400000,35.640000,0.439000,5.998000,21.400000,6.890000,6.520000,6.870000,6.980000,23.200000,8.430000,NO,9.168000,11.187200,River,41,YES,0.041561,1
54,18.900000,34.000000,0.410000,5.888000,47.600000,7.400000,7.270000,7.600000,7.000000,18.900000,14.800000,YES,8.678000,15.151200,None,55,YES,0.038684,0
55,35.400000,31.220000,0.403000,7.249000,21.900000,8.900000,8.410000,8.790000,8.690000,22.100000,4.810000,YES,7.508000,13.283200,River,50,YES,0.047985,0
56,24.700000,30.740000,0.410000,6.383000,35.700000,9.320000,8.930000,9.430000,9.070000,22.700000,5.770000,YES,5.794000,15.197600,Lake,22,YES,0.038214,0
57,31.600000,31.320000,0.411000,6.816000,40.500000,8.630000,8.280000,8.370000,8.020000,24.900000,3.950000,YES,7.432000,15.252800,Lake,45,YES,0.042595,0
58,23.300000,35.130000,0.453000,6.145000,29.200000,7.980000,7.770000,8.070000,7.440000,20.300000,6.860000,NO,7.866000,14.186400,None,22,YES,0.043784,0
59,19.600000,35.130000,0.453000,5.927000,47.200000,7.260000,6.680000,7.100000,6.680000,20.300000,9.220000,YES,6.192000,14.156800,None,20,YES,0.045900,0
60,18.700000,35.130000,0.453000,5.741000,66.200000,7.330000,7.160000,7.530000,6.880000,20.300000,13.150000,NO,7.974000,11.149600,River,30,YES,0.043823,0
61,16.000000,35.130000,0.453000,5.966000,93.400000,6.840000,6.670000,7.080000,6.690000,20.300000,14.440000,NO,6.220000,15.128000,River,48,YES,0.038611,1
62,22.200000,35.130000,0.453000,6.456000,67.800000,7.550000,7.080000,7.430000,6.840000,20.300000,6.730000,YES,5.844000,10.177600,None,56,YES,0.043332,0
63,25.000000,35.130000,0.453000,6.762000,43.400000,8.230000,7.690000,8.100000,7.910000,20.300000,9.500000,YES,5.900000,13.200000,Lake and River,28,YES,0.046951,0
64,33.000000,31.380000,0.416100,7.104000,59.500000,9.440000,9.090000,9.370000,8.990000,21.400000,8.050000,YES,8.260000,10.264000,Lake and River,30,YES,0.038989,0
65,23.500000,33.370000,0.398000,6.290000,17.800000,6.620000,6.430000,6.850000,6.550000,23.900000,4.670000,NO,9.470000,12.188000,River,20,YES,0.037496,1
66,19.400000,33.370000,0.398000,5.787000,31.100000,6.700000,6.440000,6.840000,6.460000,23.900000,10.240000,NO,8.988000,11.155200,Lake and River,44,YES,0.047876,0
67,22.000000,36.070000,0.409000,5.878000,21.400000,6.640000,6.400000,6.520000,6.430000,21.100000,8.100000,YES,7.140000,13.176000,River,29,YES,0.040528,0
68,17.400000,36.070000,0.409000,5.594000,36.800000,6.510000,6.170000,6.540000,6.770000,21.100000,13.090000,NO,8.848000,15.139200,River,40,YES,0.048421,1
69,20.900000,36.070000,0.409000,5.885000,33.000000,6.550000,6.390000,6.600000,6.460000,21.100000,8.790000,NO,8.318000,11.167200,Lake,56,YES,0.038388,0
70,24.200000,40.810000,0.413000,6.417000,6.600000,5.520000,5.070000,5.590000,4.960000,20.800000,6.720000,YES,9.784000,14.193600,River,38,YES,0.040918,1
71,21.700000,40.810000,0.413000,5.961000,17.500000,5.440000,5.200000,5.420000,5.090000,20.800000,9.880000,NO,10.034000,13.173600,Lake and River,46,YES,0.039985,0
72,22.800000,40.810000,0.413000,6.065000,7.800000,5.460000,4.960000,5.610000,5.120000,20.800000,5.520000,NO,5.856000,10.182400,River,20,YES,0.036089,0
73,23.400000,40.810000,0.413000,6.245000,6.200000,5.360000,5.230000,5.500000,5.060000,20.800000,7.540000,YES,5.968000,12.187200,Lake,45,YES,0.043323,0
74,24.100000,42.830000,0.437000,6.273000,6.000000,4.540000,3.950000,4.570000,3.950000,21.300000,6.780000,NO,7.882000,10.192800,River,40,YES,0.038894,0
75,21.400000,42.830000,0.437000,6.286000,45.000000,4.830000,4.500000,4.830000,3.860000,21.300000,8.940000,NO,6.028000,10.171200,None,28,YES,0.038145,1
76,20.000000,42.830000,0.437000,6.279000,74.500000,4.330000,3.720000,4.260000,3.900000,21.300000,11.970000,NO,7.300000,12.160000,None,22,YES,0.045275,0
77,20.800000,42.830000,0.437000,6.140000,45.800000,4.320000,4.060000,4.260000,3.720000,21.300000,10.270000,YES,5.916000,11.166400,River,57,YES,0.041829,0
78,21.200000,42.830000,0.437000,6.232000,53.700000,5.340000,5.000000,5.100000,4.620000,21.300000,12.340000,YES,8.824000,15.169600,Lake,53,YES,0.037647,1
79,20.300000,42.830000,0.437000,5.874000,36.600000,4.530000,4.230000,4.820000,4.430000,21.300000,9.100000,NO,6.406000,15.162400,Lake and River,37,YES,0.047111,1
80,28.000000,34.860000,0.426000,6.727000,33.500000,5.500000,5.280000,5.400000,5.420000,21.000000,5.290000,YES,6.460000,14.224000,Lake,54,YES,0.037354,1
81,23.900000,34.860000,0.426000,6.619000,70.400000,5.710000,5.110000,5.710000,5.080000,21.000000,7.220000,YES,5.578000,12.191200,Lake,49,YES,0.050033,0
82,24.800000,34.860000,0.426000,6.302000,32.200000,5.530000,5.190000,5.470000,5.420000,21.000000,6.720000,NO,6.096000,10.198400,River,20,YES,0.046822,0
83,22.900000,34.860000,0.426000,6.167000,46.700000,5.520000,5.180000,5.670000,5.230000,21.000000,7.510000,YES,7.558000,10.183200,Lake,34,YES,0.040449,1
84,23.900000,34.490000,0.449000,6.389000,48.000000,4.970000,4.710000,4.990000,4.450000,21.500000,9.620000,NO,6.678000,14.191200,Lake,23,YES,0.042125,0
85,26.600000,34.490000,0.449000,6.630000,56.100000,4.750000,4.150000,4.490000,4.370000,21.500000,6.530000,NO,9.732000,12.212800,River,56,YES,0.052066,1
86,22.500000,34.490000,0.449000,6.015000,45.100000,4.620000,4.160000,4.490000,4.440000,21.500000,12.860000,YES,5.950000,11.180000,River,50,YES,0.047157,1
87,22.200000,34.490000,0.449000,6.121000,56.800000,3.930000,3.740000,3.840000,3.480000,21.500000,8.440000,YES,7.244000,12.177600,None,43,YES,0.050999,0
88,23.600000,33.410000,0.489000,7.007000,86.300000,3.500000,3.090000,3.440000,3.650000,22.200000,5.500000,NO,6.972000,10.188800,River,28,YES,0.045548,1
89,28.700000,33.410000,0.489000,7.079000,63.100000,3.660000,3.380000,3.730000,2.890000,22.200000,5.700000,YES,7.574000,15.229600,None,31,YES,0.047723,1
90,22.600000,33.410000,0.489000,6.417000,66.100000,3.140000,2.930000,3.150000,3.150000,22.200000,8.810000,YES,7.352000,15.180800,Lake,58,YES,0.042303,0
91,22.000000,33.410000,0.489000,6.405000,73.900000,3.160000,2.950000,3.410000,2.850000,22.200000,8.200000,NO,8.240000,13.176000,River,23,YES,0.045096,1
92,22.900000,45.040000,0.464000,6.442000,53.600000,3.960000,3.410000,3.970000,3.320000,21.800000,8.160000,NO,9.158000,14.183200,Lake,60,YES,0.051750,1
93,25.000000,45.040000,0.464000,6.211000,28.900000,3.920000,3.550000,3.810000,3.390000,21.800000,6.210000,NO,10.300000,14.200000,Lake and River,46,YES,0.049109,1
94,20.600000,45.040000,0.464000,6.249000,77.300000,3.810000,3.340000,3.920000,3.390000,21.800000,10.590000,NO,5.712000,13.164800,Lake and River,54,YES,0.046460,1
95,28.400000,32.890000,0.445000,6.625000,57.800000,3.570000,3.230000,3.760000,3.420000,22.000000,6.650000,NO,9.968000,14.227200,River,46,YES,0.046627,1
96,21.400000,32.890000,0.445000,6.163000,69.600000,3.580000,3.350000,3.540000,3.510000,22.000000,11.340000,NO,10.228000,12.171200,River,21,YES,0.046214,1
97,38.700000,32.890000,0.445000,8.069000,76.000000,3.700000,3.320000,3.570000,3.390000,22.000000,4.210000,YES,6.274000,12.309600,River,53,YES,0.041201,1
98,43.800000,32.890000,0.445000,7.820000,36.900000,3.540000,3.420000,3.600000,3.430000,22.000000,3.570000,YES,10.876000,10.350400,Lake and River,25,YES,0.051130,0
99,33.200000,32.890000,0.445000,7.416000,62.500000,3.830000,3.360000,3.670000,3.130000,22.000000,6.190000,NO,6.564000,13.265600,River,31,YES,0.050934,1
100,27.500000,38.560000,0.520000,6.727000,79.900000,3.100000,2.680000,2.810000,2.520000,19.100000,9.420000,YES,9.650000,15.220000,Lake,24,YES,0.046955,0
101,26.500000,38.560000,0.520000,6.781000,71.300000,3.150000,2.740000,3.120000,2.420000,19.100000,7.670000,YES,7.230000,10.212000,River,58,YES,0.044415,1
102,18.600000,38.560000,0.520000,6.405000,85.400000,3.030000,2.550000,2.730000,2.550000,19.100000,10.630000,NO,6.772000,13.148800,Lake and River,57,YES,0.054341,1
103,19.300000,38.560000,0.520000,6.137000,87.400000,2.970000,2.420000,2.880000,2.580000,19.100000,13.440000,YES,6.886000,14.154400,None,36,YES,0.055407,1
104,20.100000,38.560000,0.520000,6.167000,90.000000,2.630000,2.250000,2.680000,2.130000,19.100000,12.330000,YES,7.102000,10.160800,None,20,YES,0.045729,1
105,19.500000,38.560000,0.520000,5.851000,96.700000,2.190000,1.950000,2.130000,2.150000,19.100000,16.470000,YES,7.890000,13.156000,None,57,YES,0.051421,1
106,19.500000,38.560000,0.520000,5.836000,91.900000,2.370000,2.070000,2.480000,1.920000,19.100000,18.660000,YES,10.290000,14.156000,Lake,20,YES,0.048170,0
107,20.400000,38.560000,0.520000,6.127000,85.200000,2.350000,1.950000,2.170000,2.020000,19.100000,14.090000,YES,6.008000,14.163200,Lake and River,57,YES,0.051697,0
108,19.800000,38.560000,0.520000,6.474000,97.100000,2.720000,2.180000,2.540000,2.300000,19.100000,12.270000,NO,8.596000,10.158400,Lake and River,48,YES,0.050115,0
109,19.400000,38.560000,0.520000,6.229000,91.200000,2.570000,2.280000,2.880000,2.450000,19.100000,15.550000,YES,9.788000,14.155200,None,41,YES,0.055474,0
110,21.700000,38.560000,0.520000,6.195000,54.400000,3.050000,2.600000,3.040000,2.420000,19.100000,13.000000,YES,6.934000,10.173600,None,37,YES,0.045227,0
111,22.800000,40.010000,0.547000,6.715000,81.600000,2.810000,2.630000,3.000000,2.260000,22.200000,10.160000,YES,5.656000,13.182400,River,34,YES,0.054329,1
112,18.800000,40.010000,0.547000,5.913000,92.900000,2.550000,2.230000,2.560000,2.070000,22.200000,16.210000,YES,NaN,15.150400,River,35,YES,0.057644,0
113,18.700000,40.010000,0.547000,6.092000,95.400000,2.590000,2.250000,2.550000,2.800000,22.200000,17.090000,YES,10.074000,10.149600,River,59,YES,0.060331,0
114,18.500000,40.010000,0.547000,6.254000,84.200000,2.540000,2.140000,2.290000,2.050000,22.200000,10.450000,NO,6.670000,12.148000,Lake and River,39,YES,0.056980,1
115,18.300000,40.010000,0.547000,5.928000,88.200000,2.560000,2.410000,2.720000,2.160000,22.200000,15.760000,NO,7.566000,11.146400,None,24,YES,0.053824,1
116,21.200000,40.010000,0.547000,6.176000,72.500000,2.930000,2.710000,3.000000,2.280000,22.200000,12.040000,NO,6.524000,13.169600,None,23,YES,0.052774,1
117,19.200000,40.010000,0.547000,6.021000,82.600000,2.770000,2.490000,2.920000,2.810000,22.200000,10.300000,NO,9.484000,15.153600,Lake and River,28,YES,0.060809,1
118,20.400000,40.010000,0.547000,5.872000,73.100000,2.800000,2.270000,2.620000,2.220000,22.200000,15.370000,YES,8.008000,14.163200,River,40,YES,0.056589,0
119,19.300000,40.010000,0.547000,5.731000,65.200000,2.960000,2.520000,2.920000,2.630000,22.200000,13.610000,YES,10.186000,11.154400,River,20,YES,0.052908,1
120,22.000000,55.650000,0.581000,5.870000,69.700000,2.400000,2.160000,2.530000,1.940000,20.900000,14.370000,YES,7.840000,10.176000,River,23,YES,0.056974,1
121,20.300000,55.650000,0.581000,6.004000,84.100000,2.440000,1.960000,2.370000,2.020000,20.900000,14.270000,YES,9.706000,10.162400,Lake and River,39,YES,0.056766,1
122,20.500000,55.650000,0.581000,5.961000,92.900000,2.340000,1.850000,2.270000,1.900000,20.900000,17.930000,YES,8.910000,10.164000,None,51,YES,0.060721,1
123,17.300000,55.650000,0.581000,5.856000,97.000000,2.220000,1.820000,2.070000,1.670000,20.900000,25.410000,YES,9.146000,10.138400,Lake,51,YES,0.052355,0
124,18.800000,55.650000,0.581000,5.879000,95.800000,2.210000,1.740000,2.200000,1.880000,20.900000,17.580000,NO,6.276000,13.150400,River,56,YES,0.062119,0
125,21.400000,55.650000,0.581000,5.986000,88.400000,2.130000,1.850000,2.290000,1.690000,20.900000,14.810000,YES,8.128000,14.171200,Lake,22,YES,0.060717,0
126,15.700000,55.650000,0.581000,5.613000,95.600000,1.930000,1.520000,1.800000,1.770000,20.900000,27.260000,NO,7.714000,10.125600,Lake,42,YES,0.063462,0
127,16.200000,51.890000,0.624000,5.693000,96.000000,2.090000,1.730000,1.840000,1.490000,18.800000,17.190000,YES,5.924000,15.129600,None,31,YES,0.056660,0

**Let us now see the number of variables and observations in the data.**

In [22]:
# use 'shape' to check the dimension of data
df_houseprice.shape

(506, 19)

# Check the Data Type

In [23]:
# use 'dtypes' to check the data type of a variable
df_houseprice.dtypes

price          float64
resid_area     float64
air_qual       float64
room_num       float64
age            float64
dist1          float64
dist2          float64
dist3          float64
dist4          float64
teachers       float64
poor_prop      float64
airport         object
n_hos_beds     float64
n_hot_rooms    float64
waterbody       object
rainfall         int64
bus_ter         object
parks          float64
Sold             int64
dtype: object

**Interpretation:** The variables `price`, `Sold`, `resid_area`, `air_qual`, `room_num`, `age`,
    `dist1`, `dist2`, `dist3`, `dist4`, `teachers`, `poor_prop`,`n_hos_beds`, `n_hot_rooms`, `rainfall`,`parks` are numerical.

From the above output, we see that the data type of `bus_ter`,`waterbody`, `airport` are the 'Catagorical'.


And all veriables in Correct Datatypes

# Remove Insignificant Variables

In [24]:
# First Check Catagorical Columns
df_cat = df_houseprice.select_dtypes(include='object')
df_cat.head()

  airport waterbody bus_ter
0     YES     River     YES
1      NO      Lake     YES
2      NO      None     YES
3     YES      Lake     YES
4      NO      Lake     YES

In [25]:
df_num = df_houseprice.select_dtypes(include=['int','float'])
df_num.head()

,price,resid_area,air_qual,room_num,age,dist1,dist2,dist3,dist4,teachers,poor_prop,n_hos_beds,n_hot_rooms,rainfall,parks,Sold
0,24.000000,32.310000,0.538000,6.575000,65.200000,4.350000,3.810000,4.180000,4.010000,24.700000,4.980000,5.480000,11.192000,23,0.049347,0
1,21.600000,37.070000,0.469000,6.421000,78.900000,4.990000,4.700000,5.120000,5.060000,22.200000,9.140000,7.332000,12.172800,42,0.046146,1
2,34.700000,37.070000,0.469000,7.185000,61.100000,5.030000,4.860000,5.010000,4.970000,22.200000,4.030000,7.394000,101.120000,38,0.045764,0
3,33.400000,32.180000,0.458000,6.998000,45.800000,6.210000,5.930000,6.160000,5.960000,21.300000,2.940000,9.268000,11.267200,45,0.047151,0
4,36.200000,32.180000,0.458000,7.147000,54.200000,6.160000,5.860000,6.370000,5.860000,21.300000,5.330000,8.824000,11.289600,55,0.039474,0

In [26]:
df_cat.bus_ter.value_counts()

YES    506
Name: bus_ter, dtype: int64

In [27]:
# So as we see here Bus_ter column have only one unique value that means it wont be usefull for our analysis
df_houseprice.drop("bus_ter",axis =1,inplace = True)

<a id="null"></a>
## 2.5 Missing Value Treatment

First run a check for the presence of missing values and their percentage for each column. Then choose the right approach to treat them.

In [28]:
df_houseprice.isnull().sum()

price          0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     8
n_hot_rooms    0
waterbody      0
rainfall       0
parks          0
Sold           0
dtype: int64

In [30]:
df_houseprice=df_houseprice.dropna()
df_houseprice.isnull().sum()

price          0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     0
n_hot_rooms    0
waterbody      0
rainfall       0
parks          0
Sold           0
dtype: int64

<a id="dummy"></a>
## 2.8 Dummy Encode the Categorical Variables

#### Split the dependent and independent variables.

In [31]:
df_target = df_houseprice['Sold']

df_feature = df_houseprice.drop('price', axis = 1)

#### Filter numerical and categorical variables.

In [32]:
df_num = df_feature.select_dtypes(include = [np.number])

# display numerical features
df_num.head()

,resid_area,air_qual,room_num,age,dist1,dist2,dist3,dist4,teachers,poor_prop,n_hos_beds,n_hot_rooms,rainfall,parks,Sold
0,32.310000,0.538000,6.575000,65.200000,4.350000,3.810000,4.180000,4.010000,24.700000,4.980000,5.480000,11.192000,23,0.049347,0
1,37.070000,0.469000,6.421000,78.900000,4.990000,4.700000,5.120000,5.060000,22.200000,9.140000,7.332000,12.172800,42,0.046146,1
2,37.070000,0.469000,7.185000,61.100000,5.030000,4.860000,5.010000,4.970000,22.200000,4.030000,7.394000,101.120000,38,0.045764,0
3,32.180000,0.458000,6.998000,45.800000,6.210000,5.930000,6.160000,5.960000,21.300000,2.940000,9.268000,11.267200,45,0.047151,0
4,32.180000,0.458000,7.147000,54.200000,6.160000,5.860000,6.370000,5.860000,21.300000,5.330000,8.824000,11.289600,55,0.039474,0

In [33]:
df_cat = df_feature.select_dtypes(include = 'object')
df_cat.columns

Index(['airport', 'waterbody'], dtype='object')

In [34]:
dummy_var = pd.get_dummies(data = df_cat, drop_first = True)
dummy_var.head()

   airport_YES  waterbody_Lake and River  waterbody_None  waterbody_River
0            1                         0               0                1
1            0                         0               0                0
2            0                         0               1                0
3            1                         0               0                0
4            0                         0               0                0

# Scale the Data

In [35]:
target = df_houseprice['Sold']

In [36]:
scaler = StandardScaler()
scaled = scaler.fit_transform(df_num)

df_scaled = pd.DataFrame(scaled, columns = df_num.columns)

In [37]:
df_scaled.head(3)

,resid_area,air_qual,room_num,age,dist1,dist2,dist3,dist4,teachers,poor_prop,n_hos_beds,n_hot_rooms,rainfall,parks,Sold
0,-1.282444,-0.137094,0.408975,-0.115644,0.172845,0.079578,0.097320,0.180490,1.462167,-1.066368,-1.640299,-0.352111,-1.302068,-0.473132,-0.911527
1,-0.590059,-0.733195,0.189974,0.369741,0.476100,0.501123,0.540095,0.679821,0.304963,-0.484136,-0.384875,-0.166019,0.215194,-0.775225,1.097060
2,-0.590059,-0.733195,1.276446,-0.260905,0.495053,0.576906,0.488281,0.637021,0.304963,-1.199330,-0.342847,16.710340,-0.104230,-0.811237,-0.911527

#### Concatenate scaled numerical and dummy encoded categorical variables.

In [38]:
X = pd.concat([df_scaled, dummy_var], axis = 1)
X.drop("Sold",axis = 1,inplace = True)
# display first five observations
X.head()

,resid_area,air_qual,room_num,age,dist1,dist2,dist3,dist4,teachers,poor_prop,n_hos_beds,n_hot_rooms,rainfall,parks,airport_YES,waterbody_Lake and River,waterbody_None,waterbody_River
0,-1.282444,-0.137094,0.408975,-0.115644,0.172845,0.079578,0.097320,0.180490,1.462167,-1.066368,-1.640299,-0.352111,-1.302068,-0.473132,1.000000,0.000000,0.000000,1.000000
1,-0.590059,-0.733195,0.189974,0.369741,0.476100,0.501123,0.540095,0.679821,0.304963,-0.484136,-0.384875,-0.166019,0.215194,-0.775225,0.000000,0.000000,0.000000,0.000000
2,-0.590059,-0.733195,1.276446,-0.260905,0.495053,0.576906,0.488281,0.637021,0.304963,-1.199330,-0.342847,16.710340,-0.104230,-0.811237,0.000000,0.000000,1.000000,0.000000
3,-1.301354,-0.828226,1.010516,-0.802977,1.054179,1.083708,1.029975,1.107818,-0.111631,-1.351886,0.927490,-0.337843,0.454762,-0.680402,1.000000,0.000000,0.000000,0.000000
4,-1.301354,-0.828226,1.222407,-0.505369,1.030487,1.050552,1.128893,1.060263,-0.111631,-1.017382,0.626514,-0.333593,1.253320,-1.404723,0.000000,0.000000,0.000000,0.000000

# Train-Test Split

In [39]:
X = sm.add_constant(X)

X_train, X_test, y_train, y_test = train_test_split(X, target, random_state = 10, test_size = 0.2)

# check the dimensions of the train & test subset using 'shape'
# print dimension of train set
print('X_train', X_train.shape)
print('y_train', y_train.shape)

# print dimension of test set
print('X_test', X_test.shape)
print('y_test', y_test.shape)

ValueError: Found input variables with inconsistent numbers of samples: [506, 498]

# Decision Tree for Classification

In [ ]:
decision_tree_classification = DecisionTreeClassifier(criterion = 'gini', random_state = 10)

# fit the model using fit() on train data
decision_tree = decision_tree_classification.fit(X_train, y_train)

**Calculate performance measures on the train set.**

In [ ]:
train_pred = decision_tree_classification.predict(X_train)

In [ ]:
print(classification_report(y_train, train_pred))

In [ ]:
test_pred = decision_tree_classification.predict(X_test)
print(classification_report(y_test, test_pred))

In [ ]:
y_test

In [ ]:
test_pred

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,test_pred)